version: '3'

services:
  backend:
    # this is our custom drupal image residing in
    # wcms-drupal-apache/Dockerfile
    image: quiltdata/lambda
    container_name: aws-lambda
  frontend:
    build: ./angular-frontend
    container_name: angular-client
      # This line maps the contents of the client folder into the container.
    volumes:
      - ./angular-frontend:/usr/src/app
  nginx:
    build: ./nginx
    # Map Nginx port 80 to the local machine's port 80
    ports:
      - "80:80"
    # Link the client container so that Nginx will have access to it
    links:
      - frontend